### ISSUE TITLE
Estante de materiais do usuário

### ISSUE THREAD

**Issue by anaveroneze** [Projeto-de-Software-1/bricademy#3]
Criar flag que indica se o material está anunciado ou não

**Comment by anaveroneze** [comment]
Configurar a adição de fotos do material

**Comment by anaveroneze** [comment]
Possibilidade de excluir um material (criar view)

**Comment by doyleSM** [comment]
> Possibilidade de excluir um material (criar view)
vamos fazer a solicitação primeiro, fica mais fácil de verificar daí
